spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/crypto
  liquibase:
    enabled: true
  jpa:
    show-sql: true
CryptoApi:
  url: https://api.coinlore.net/api/ticker/?id=
  cryptosId: 90, 80, 48543
  scheduled:
    cron:
      expression: 0 * * * * *